# Generated by Django 2.2.16 on 2021-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaType', models.CharField(max_length=100, verbose_name='Pizza Type')),
                ('pizzaSize', models.CharField(max_length=100)),
                ('toppings', models.CharField(max_length=100)),
            ],
        ),
    ]
